### ISSUE TITLE
problems with schema-generation with hibernate-5.1.0.Final

### ISSUE THREAD

**Issue by romanstumm** [divinespear/jpa-schema-gradle-plugin#20]
jpa-schema-gradle-plugin works well with hibernate-5.0.8.Final but schema generation writes corrupt files or appends the DDL to the existing output files instead of replacing the file with hibernate-5.1.0.Final. Maybe the hibernate schema generation tooling API has changed?

Example:

dependencies:

io.github.divinespear:jpa-schema-gradle-plugin:0.2.0-1
org.hibernate:hibernate-entitymanager:5.1.0.Final
org.hibernate:hibernate-java8:5.1.0.Final

generateSchema {
    format = true
    persistenceUnitName = 'test'
    databaseProductName = 'PostgreSQL'
    databaseMajorVersion = 9
    databaseMinorVersion = 4
    jdbcDriver = 'org.postgresql.Driver'
    scriptAction = 'create'
    outputDirectory = project.file('src/main/resources/database')
    createOutputFileName = 'schema.sql'
    dropOutputFileName = 'drop.sql'
    jdbcUrl = 'jdbc:postgresql://localhost:5432/postgres'
    jdbcUser = 'postgres'
    jdbcPassword = 'test'
}

**Comment by remmeier** [comment]
I probably have the same issues. I think the postprocessing is broken. It should not do anything if format=false was specified. Actually I configured the hibernate formatter:

`<property name="hibernate.format_sql" value="true" />`

in the persistence.xml. He does seem to make quite a good job. There are only minor identation issues for create-table. 

I think this project should upgrade to Hibernate 5.1. While 5.0.x was attempting to create DB connections, it does not seem to be the case anymore with Hibernate 5.1

**Comment by Ramblurr** [comment]
Things seem to be working fine for me with hibernate 5.2.3.Final. However make sure you add the

```
        classpath "io.github.divinespear:jpa-schema-gradle-plugin:+"
        classpath "org.hibernate:hibernate-entitymanager:5.2.3.Final"
        classpath "org.hibernate:hibernate-java8:5.2.3.Final"
```
to the buildscript deps section in addition to your normal dependencies

**Comment by Ramblurr** [comment]
So i've worked around this by adding 2 new tasks to my build script:

```

task deleteSchema(type: Delete) {
    delete './build/generated-schema/create.sql'
}

task schema(dependsOn: ['deleteSchema', 'generateSchema'])
```

Then I use `gradle schema` to generate the schema.

**Comment by divinespear** [comment]
Thanks for report.
I'll check it soon.

**Comment by divinespear** [comment]
@romanstumm @remmeier @Ramblurr would you share expected and actual generated ddl?
I cannot reproduce this issue :/

**Comment by Ramblurr** [comment]
Now with the latest version of the plugin (0.2.1) and hibernate 5.1.2.Final I'm getting:

```
Caused by: java.lang.NoSuchMethodError: org.hibernate.tool.schema.internal.SchemaDropperImpl: method <init>()V not found
        at org.hibernate.jpa.internal.schemagen.GenerationSourceFromMetadata.getCommands(GenerationSourceFromMetadata.java:43)
        at org.hibernate.jpa.internal.schemagen.JpaSchemaGenerator.doGeneration(JpaSchemaGenerator.java:492)
        at org.hibernate.jpa.internal.schemagen.JpaSchemaGenerator.access$300(JpaSchemaGenerator.java:55)
        at org.hibernate.jpa.internal.schemagen.JpaSchemaGenerator$GenerationProcess.execute(JpaSchemaGenerator.java:171)
        at org.hibernate.jpa.internal.schemagen.JpaSchemaGenerator.performGeneration(JpaSchemaGenerator.java:65)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.generateSchema(EntityManagerFactoryBuilderImpl.java:861)
        at org.hibernate.jpa.HibernatePersistenceProvider.generateSchema(HibernatePersistenceProvider.java:143)
        at io.github.divinespear.gradle.plugin.JpaSchemaGenerateTask.xmllessGenerate(JpaSchemaGenerateTask.groovy:428)
        at io.github.divinespear.gradle.plugin.JpaSchemaGenerateTask$_generate_closure12.doCall(JpaSchemaGenerateTask.groovy:362)
        at io.github.divinespear.gradle.plugin.JpaSchemaGenerateTask.generate(JpaSchemaGenerateTask.groovy:336)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

**Comment by Ramblurr** [comment]
Yea,  a simple test is now showing me that this plugin doesn't work with 5.1.x, but it does work with 5.0 and 5.2

**Comment by divinespear** [comment]
It is fixed with #31.
